package cue

func getLedFromWindowsKeyId(windowsKeyId int) (Led, bool) {
	switch windowsKeyId {
	case 0x03:
		return GetLedById(CLK_PauseBreak)
	case 0x08:
		return GetLedById(CLK_Backspace)
	case 0x09:
		return GetLedById(CLK_Tab)
	case 0x0D:
		return GetLedById(CLK_Enter)
	case 0x10:
		return GetLedById(CLK_LeftShift)
	case 0x11:
		return GetLedById(CLK_LeftCtrl)
	case 0x12:
		return GetLedById(CLK_LeftAlt)
	case 0x13:
		return GetLedById(CLK_PauseBreak)
	case 0x14:
		return GetLedById(CLK_CapsLock)
	case 0x1B:
		return GetLedById(CLK_Escape)
	case 0x20:
		return GetLedById(CLK_Space)
	case 0x21:
		return GetLedById(CLK_PageUp)
	case 0x22:
		return GetLedById(CLK_PageDown)
	case 0x23:
		return GetLedById(CLK_End)
	case 0x24:
		return GetLedById(CLK_Home)
	case 0x25:
		return GetLedById(CLK_LeftArrow)
	case 0x26:
		return GetLedById(CLK_UpArrow)
	case 0x27:
		return GetLedById(CLK_RightArrow)
	case 0x28:
		return GetLedById(CLK_DownArrow)
	case 0x2C:
		return GetLedById(CLK_PrintScreen)
	case 0x2D:
		return GetLedById(CLK_Insert)
	case 0x2E:
		return GetLedById(CLK_Delete)
	case 0x30:
		return GetLedById(CLK_0)
	case 0x31:
		return GetLedById(CLK_1)
	case 0x32:
		return GetLedById(CLK_2)
	case 0x33:
		return GetLedById(CLK_3)
	case 0x34:
		return GetLedById(CLK_4)
	case 0x35:
		return GetLedById(CLK_5)
	case 0x36:
		return GetLedById(CLK_6)
	case 0x37:
		return GetLedById(CLK_7)
	case 0x38:
		return GetLedById(CLK_8)
	case 0x39:
		return GetLedById(CLK_9)
	case 0x41:
		return GetLedById(CLK_A)
	case 0x42:
		return GetLedById(CLK_B)
	case 0x43:
		return GetLedById(CLK_C)
	case 0x44:
		return GetLedById(CLK_D)
	case 0x45:
		return GetLedById(CLK_E)
	case 0x46:
		return GetLedById(CLK_F)
	case 0x47:
		return GetLedById(CLK_G)
	case 0x48:
		return GetLedById(CLK_H)
	case 0x49:
		return GetLedById(CLK_I)
	case 0x4A:
		return GetLedById(CLK_J)
	case 0x4B:
		return GetLedById(CLK_L)
	case 0x4C:
		return GetLedById(CLK_M)
	case 0x4D:
		return GetLedById(CLK_N)
	case 0x4E:
		return GetLedById(CLK_O)
	case 0x4F:
		return GetLedById(CLK_P)
	case 0x50:
		return GetLedById(CLK_Q)
	case 0x51:
		return GetLedById(CLK_R)
	case 0x52:
		return GetLedById(CLK_S)
	case 0x53:
		return GetLedById(CLK_T)
	case 0x54:
		return GetLedById(CLK_U)
	case 0x55:
		return GetLedById(CLK_V)
	case 0x56:
		return GetLedById(CLK_W)
	case 0x57:
		return GetLedById(CLK_X)
	case 0x58:
		return GetLedById(CLK_Y)
	case 0x59:
		return GetLedById(CLK_Z)
	case 0x5B:
		return GetLedById(CLH_LeftLogo)
	case 0x5C:
		return GetLedById(CLH_RightLogo)
	case 0x5D:
		return GetLedById(CLK_Application)
	case 0x60:
		return GetLedById(CLK_Keypad0)
	case 0x61:
		return GetLedById(CLK_Keypad1)
	case 0x62:
		return GetLedById(CLK_Keypad2)
	case 0x63:
		return GetLedById(CLK_Keypad3)
	case 0x64:
		return GetLedById(CLK_Keypad4)
	case 0x65:
		return GetLedById(CLK_Keypad5)
	case 0x66:
		return GetLedById(CLK_Keypad6)
	case 0x67:
		return GetLedById(CLK_Keypad7)
	case 0x68:
		return GetLedById(CLK_Keypad8)
	case 0x69:
		return GetLedById(CLK_Keypad9)
	case 0x6A:
		return GetLedById(CLK_KeypadAsterisk)
	case 0x6B:
		return GetLedById(CLK_KeypadPlus)
	case 0x6C:
		return GetLedById(CLK_KeypadAsterisk)
	case 0x6D:
		return GetLedById(CLK_KeypadMinus)
	case 0x6E:
		return GetLedById(CLK_KeypadPeriodAndDelete)
	case 0x6F:
		return GetLedById(CLK_KeypadSlash)
	case 0x70:
		return GetLedById(CLK_F1)
	case 0x71:
		return GetLedById(CLK_F2)
	case 0x72:
		return GetLedById(CLK_F3)
	case 0x73:
		return GetLedById(CLK_F4)
	case 0x74:
		return GetLedById(CLK_F5)
	case 0x75:
		return GetLedById(CLK_F6)
	case 0x76:
		return GetLedById(CLK_F7)
	case 0x77:
		return GetLedById(CLK_F8)
	case 0x78:
		return GetLedById(CLK_F9)
	case 0x79:
		return GetLedById(CLK_F10)
	case 0x7A:
		return GetLedById(CLK_F11)
	case 0x7B:
		return GetLedById(CLK_F12)
	case 0x90:
		return GetLedById(CLK_NumLock)
	case 0x91:
		return GetLedById(CLK_ScrollLock)
	case 0xA0:
		return GetLedById(CLK_LeftShift)
	case 0xA1:
		return GetLedById(CLK_RightShift)
	case 0xA2:
		return GetLedById(CLK_LeftCtrl)
	case 0xA3:
		return GetLedById(CLK_RightCtrl)
	case 0xA4:
		return GetLedById(CLK_LeftGui)
	case 0xA5:
		return GetLedById(CLK_RightGui)
	case 0xAD:
		return GetLedById(CLK_Mute)
	case 0xAE:
		return GetLedById(CLK_VolumeDown)
	case 0xAF:
		return GetLedById(CLK_VolumeUp)
	case 0xB0:
		return GetLedById(CLK_ScanNextTrack)
	case 0xB1:
		return GetLedById(CLK_ScanPreviousTrack)
	case 0xB2:
		return GetLedById(CLK_Stop)
	case 0xB3:
		return GetLedById(CLK_PlayPause)
	case 0xBA:
		return GetLedById(CLK_SemicolonAndColon)
	case 0xBB:
		return GetLedById(CLK_EqualsAndPlus)
	case 0xBC:
		return GetLedById(CLK_CommaAndLessThan)
	case 0xBD:
		return GetLedById(CLK_MinusAndUnderscore)
	case 0xBE:
		return GetLedById(CLK_PeriodAndBiggerThan)
	case 0xBF:
		return GetLedById(CLK_SlashAndQuestionMark)
	case 0xC0:
		return GetLedById(CLK_GraveAccentAndTilde)
	case 0xDB:
		return GetLedById(CLK_BracketLeft)
	case 0xDC:
		return GetLedById(CLK_Backslash)
	case 0xDD:
		return GetLedById(CLK_BracketRight)
	case 0xDE:
		return GetLedById(CLK_ApostropheAndDoubleQuote)
	default:
		return Led{}, false
	}
}
